// Reviewed against the immutable revisions in sources.lock.json.
export const baseUrl = "https://api.bonyanoss.org";
export const pair = (en, ar) => ({ en, ar });
const p = (name, location, required, schema, example, en, ar) => ({
  name,
  in: location,
  required,
  schema,
  example,
  description: pair(en, ar),
});
const surah = (name = "surah") =>
  p(
    name,
    "path",
    true,
    { type: "integer", minimum: 1, maximum: 114 },
    1,
    "Surah number, 1 through 114.",
    "رقم السورة من 1 إلى 114.",
  );
const aya = (name = "aya") =>
  p(
    name,
    "path",
    true,
    { type: "integer", minimum: 1 },
    1,
    "Verse number within the surah. An empty lookup returns 404; tafsir provider rejection can instead produce 503 when every configured source fails.",
    "رقم الآية داخل السورة. النتيجة الفارغة تعيد 404؛ وقد يعيد رفض مصادر التفسير 503 عند فشل جميع المصادر المضبوطة.",
  );
const reciter = () =>
  p(
    "id",
    "path",
    true,
    { type: "integer" },
    1,
    "ID returned by the reciter catalogue. IDs depend on the provider.",
    "المعرّف الذي يعيده فهرس القراء. المعرّفات مرتبطة بالمصدر.",
  );
const name = () =>
  p(
    "name",
    "query",
    true,
    { type: "string", minLength: 1 },
    "الفاتحة",
    "Arabic name or substring. Use Arabic input; Latin-only input is not a supported search.",
    "الاسم العربي أو جزء منه. استخدم العربية؛ البحث بحروف لاتينية فقط غير مدعوم.",
  );
const search = (max) => [
  p(
    "text",
    "query",
    true,
    { type: "string", minLength: 1 },
    "الرحمن",
    "Arabic substring, URL-encoded. Blank input returns 400.",
    "جزء من نص عربي مع ترميز URL. الإدخال الفارغ يعيد 400.",
  ),
  p(
    "limit",
    "query",
    false,
    { type: "integer", default: 50, minimum: 1, maximum: max },
    10,
    `Result cap, not pagination. The server clamps to 1..${max}; zero or an unparsable value falls back to 50.`,
    `حد النتائج وليس ترقيم صفحات. يضبطه الخادم بين 1 و${max}؛ الصفر أو القيمة غير القابلة للتحليل تعود إلى 50.`,
  ),
];
const edition = () =>
  p(
    "edition",
    "path",
    true,
    {
      type: "string",
      enum: ["muyassar", "jalalayn", "saadi", "waseet", "qurtubi"],
    },
    "muyassar",
    "Public edition ID from GET /tafsir. Use muyassar, not ar.muyassar.",
    "معرّف النسخة من GET /tafsir. استخدم muyassar وليس ar.muyassar.",
  );
const book = () =>
  p(
    "book",
    "path",
    true,
    { type: "string", minLength: 1 },
    "bukhari",
    "Book ID from GET /hadith. Unknown IDs can return 503 when both providers reject them.",
    "معرّف الكتاب من GET /hadith. قد يعيد المعرّف المجهول 503 إذا رفضه المصدران.",
  );
const date = (required = false, hijri = false) =>
  p(
    "date",
    "query",
    required,
    { type: "string", pattern: "^\\d{2}-\\d{2}-\\d{4}$" },
    hijri ? "01-09-1447" : "01-01-2026",
    `${hijri ? "Hijri" : "Gregorian"} date in DD-MM-YYYY. ${required ? "Required." : "Omitted or blank uses the API server’s current date."} Validation checks the format, not calendar validity.`,
    `تاريخ ${hijri ? "هجري" : "ميلادي"} بصيغة DD-MM-YYYY. ${required ? "مطلوب." : "عند حذفه أو تركه فارغًا يستخدم تاريخ خادم API الحالي."} التحقق من الصيغة فقط، وليس صحة اليوم في التقويم.`,
  );
const coords = (required, bounds) => [
  p(
    "latitude",
    "query",
    required,
    { type: "number", ...(bounds ? { minimum: -90, maximum: 90 } : {}) },
    21.4225,
    "Latitude in decimal degrees; provide it together with longitude.",
    "خط العرض بالدرجات العشرية؛ أرسله مع خط الطول.",
  ),
  p(
    "longitude",
    "query",
    required,
    { type: "number", ...(bounds ? { minimum: -180, maximum: 180 } : {}) },
    39.8262,
    "Longitude in decimal degrees; provide it together with latitude.",
    "خط الطول بالدرجات العشرية؛ أرسله مع خط العرض.",
  ),
];
const e = (
  path,
  slug,
  id,
  title,
  description,
  schema,
  params = [],
  sdk = null,
  errors = [503],
  notes = null,
) => ({
  path,
  slug,
  id,
  title: pair(...title),
  description: pair(...description),
  schema,
  params,
  sdk,
  errors,
  notes: notes ? pair(...notes) : null,
});
export const endpoints = [
  e(
    "/",
    "meta/catalogue",
    "getCatalogue",
    ["Route catalogue", "فهرس المسارات"],
    [
      "Lists registered content routes and project metadata. The four operational routes are excluded from the catalogue.",
      "يعرض مسارات المحتوى المسجّلة وبيانات المشروع. لا يدرج مسارات التشغيل الأربعة.",
    ],
    "Catalogue",
    [],
    "client.routes()",
    [],
  ),
  e(
    "/health",
    "meta/health",
    "getHealth",
    ["Liveness", "فحص الحياة"],
    [
      "Confirms the HTTP process responds. It does not contact content providers.",
      "يتحقق من استجابة عملية HTTP. لا يتصل بمصادر المحتوى.",
    ],
    "Health",
    [],
    "client.health()",
    [],
  ),
  e(
    "/ready",
    "meta/ready",
    "getReady",
    ["Readiness and cache", "الجاهزية والكاش"],
    [
      "Returns process readiness and current cache counts. This is not an upstream availability check.",
      "يعيد جاهزية العملية وأعداد عناصر الكاش الحالية. لا يفحص توفر المصادر الخارجية.",
    ],
    "Ready",
    [],
    "client.ready()",
    [],
  ),
  e(
    "/metrics",
    "meta/metrics",
    "getMetrics",
    ["Prometheus metrics", "مقاييس Prometheus"],
    [
      "Returns uptime, cache gauges and upstream request counters as text.",
      "يعيد مدة التشغيل ومقاييس الكاش وعدادات طلبات المصادر كنص.",
    ],
    "Metrics",
    [],
    "client.metrics()",
    [],
  ),
  e(
    "/surah",
    "surah/list",
    "listSurahs",
    ["List surahs", "قائمة السور"],
    [
      "Returns the chapter catalogue in data.surah. This endpoint returns names and metadata, not verse text.",
      "يعيد فهرس السور داخل data.surah. يحتوي أسماء وبيانات السور دون نص الآيات.",
    ],
    "SurahListResponse",
    [],
    "client.surah.list()",
  ),
  e(
    "/surah/{id}",
    "surah/get",
    "getSurah",
    ["Get a surah", "بيانات سورة"],
    ["Returns metadata for one surah.", "يعيد بيانات سورة واحدة."],
    "SurahResponse",
    [surah("id")],
    "client.surah.getById(1)",
    [400, 404, 503],
  ),
  e(
    "/surah/search",
    "surah/search",
    "searchSurahs",
    ["Search surah names", "البحث في أسماء السور"],
    [
      "Matches a normalized Arabic substring and returns an array. No matches returns 404.",
      "يطابق جزءًا من الاسم بعد تطبيع العربية ويعيد مصفوفة. تعاد 404 عند غياب النتائج.",
    ],
    "SurahSearchResponse",
    [name()],
    "client.surah.search('الفاتحة')",
    [400, 404, 503],
  ),
  e(
    "/ayat",
    "ayat/all",
    "listAyat",
    ["Full Quran text", "نص القرآن كاملًا"],
    [
      "Returns all available surahs and verses in data.surahs. This is a large response without pagination.",
      "يعيد السور والآيات المتاحة داخل data.surahs. الاستجابة كبيرة ولا تدعم ترقيم الصفحات.",
    ],
    "AyatCorpusResponse",
    [],
    "client.ayat.list()",
  ),
  e(
    "/ayat/{id}",
    "ayat/get-by-number",
    "getAyaByNumber",
    ["Aya by global number", "آية برقمها العام"],
    [
      "Looks up a verse by its global Quran number, rather than its position within a surah.",
      "يبحث عن آية برقمها العام في القرآن، وليس ترتيبها داخل السورة.",
    ],
    "AyaLookupResponse",
    [
      p(
        "id",
        "path",
        true,
        { type: "integer", minimum: 1, maximum: 6236 },
        1,
        "Global verse number, 1 through 6236.",
        "رقم الآية العام من 1 إلى 6236.",
      ),
    ],
    "client.ayat.getById(1)",
    [400, 404, 503],
  ),
  e(
    "/ayat/{surah}/aya/{id}",
    "ayat/get-by-surah-aya",
    "getAyaBySurah",
    ["Aya within a surah", "آية داخل سورة"],
    [
      "Returns one verse with its surah number and name.",
      "يعيد آية واحدة مع رقم السورة واسمها.",
    ],
    "AyaLookupResponse",
    [surah(), aya("id")],
    "client.ayat.getBySurah(1, 1)",
    [400, 404, 503],
  ),
  e(
    "/ayat/search",
    "ayat/search",
    "searchAyat",
    ["Search Quran text", "البحث في نص القرآن"],
    [
      "Returns {success, total, data: [...]}. total counts returned matches after the limit, not all matches in the Quran.",
      "يعيد {success, total, data: [...]}. يحسب total النتائج المعادة بعد تطبيق الحد، وليس جميع التطابقات في القرآن.",
    ],
    "AyaSearchResponse",
    search(500),
    null,
    [400, 404, 503],
    [
      "SDK 1.0.2 has an envelope mismatch in client.ayat.search(). Use the fetch example here or the compatibility helper in the SDK guide.",
      "توجد مشكلة في فك الاستجابة داخل client.ayat.search() في SDK 1.0.2. استخدم مثال fetch هنا أو الدالة البديلة في دليل SDK.",
    ],
  ),
  e(
    "/reciters",
    "reciters/list",
    "listReciters",
    ["List reciters", "قائمة القراء"],
    [
      "Returns reciters in data.reciters. The fallback provider may omit moshaf and audio-server information.",
      "يعيد القراء داخل data.reciters. قد يحذف المصدر البديل المصاحف وبيانات خادم الصوت.",
    ],
    "ReciterCollectionResponse",
    [],
    "client.reciters.list()",
  ),
  e(
    "/reciters/{id}",
    "reciters/get",
    "getReciter",
    ["Get a reciter", "بيانات قارئ"],
    [
      "Looks up an ID in the currently cached provider catalogue.",
      "يبحث عن المعرّف في فهرس المصدر المخزّن حاليًا.",
    ],
    "ReciterResponse",
    [reciter()],
    "client.reciters.getById(1)",
    [400, 404, 503],
  ),
  e(
    "/reciters/search",
    "reciters/search",
    "searchReciters",
    ["Search reciter names", "البحث في أسماء القراء"],
    [
      "Returns matching reciters using Arabic substring matching. This is not fuzzy or English-language search.",
      "يعيد القراء المطابقين لجزء من الاسم العربي. لا يدعم البحث التقريبي أو البحث الإنجليزي.",
    ],
    "ReciterSearchResponse",
    [{ ...name(), example: "العفاسي" }],
    "client.reciters.search('العفاسي')",
    [400, 404, 503],
  ),
  e(
    "/reciters/{id}/surah/{surah}",
    "reciters/audio",
    "getReciterAudio",
    ["Surah audio URL", "رابط صوت السورة"],
    [
      "Builds a URL from the first moshaf server and a three-digit surah number. Returns JSON, not an audio stream.",
      "ينشئ الرابط من خادم أول مصحف ورقم السورة بثلاث خانات. يعيد JSON وليس بثًا صوتيًا.",
    ],
    "ReciterAudioResponse",
    [reciter(), surah()],
    "client.reciters.getSurah(1, 1)",
    [400, 404, 503],
    [
      "The API does not verify that the MP3 exists. A reciter from quran.com may have no moshaf, causing 404. Discover a reciter with moshaf before requesting audio.",
      "لا يتحقق API من وجود ملف MP3. قد يفتقد قارئ من quran.com بيانات المصحف فتُعاد 404. اختر قارئًا له moshaf قبل طلب الصوت.",
    ],
  ),
  e(
    "/tafsir",
    "tafsir/editions",
    "listTafsirEditions",
    ["Tafsir editions", "نسخ التفسير"],
    [
      "Lists the five configured public edition IDs and Arabic labels. The catalogue is local; it does not test provider availability.",
      "يعرض معرّفات نسخ التفسير الخمس وأسماءها العربية. الفهرس محلي ولا يفحص توفر المصادر.",
    ],
    "TafsirEditionListResponse",
    [],
    "client.tafsir.listEditions()",
    [],
  ),
  e(
    "/tafsir/{edition}/{surah}",
    "tafsir/surah",
    "getSurahTafsir",
    ["Tafsir for a surah", "تفسير سورة"],
    [
      "Returns an array, including when the optional aya filter selects one verse. Returned edition is a provider-specific ID.",
      "يعيد مصفوفة حتى عند تحديد آية واحدة بالمعامل aya. حقل edition المعاد يستخدم معرّف المصدر.",
    ],
    "TafsirListResponse",
    [
      edition(),
      surah(),
      p(
        "aya",
        "query",
        false,
        { type: "integer", minimum: 1 },
        1,
        "Optional verse within the surah. The response remains an array.",
        "آية اختيارية داخل السورة. تبقى الاستجابة مصفوفة.",
      ),
    ],
    "client.tafsir.forSurah('muyassar', 1)",
    [400, 404, 503],
  ),
  e(
    "/tafsir/{edition}/{surah}/{aya}",
    "tafsir/aya",
    "getAyaTafsir",
    ["Tafsir for an aya", "تفسير آية"],
    [
      "Returns one tafsir object. muyassar can use two sources; the other configured editions each have one source.",
      "يعيد كائن تفسير واحد. لنسخة muyassar مصدران، ولكل نسخة أخرى مصدر واحد.",
    ],
    "TafsirItemResponse",
    [edition(), surah(), aya()],
    "client.tafsir.forAya('muyassar', 1, 1)",
    [400, 404, 503],
  ),
  e(
    "/azkar",
    "azkar/categories",
    "listAzkarCategories",
    ["Azkar categories", "تصنيفات الأذكار"],
    [
      "Lists category names, item counts and sources in data.categories.",
      "يعرض أسماء التصنيفات وأعداد الأذكار ومصادرها داخل data.categories.",
    ],
    "AzkarCategorySummaryResponse",
    [],
    "client.azkar.listCategories()",
  ),
  e(
    "/azkar/{category}",
    "azkar/category",
    "getAzkarCategory",
    ["Azkar in a category", "أذكار تصنيف"],
    [
      "Returns the first category whose normalized Arabic name contains the supplied value. Use the full name from the catalogue to avoid ambiguous matches.",
      "يعيد أول تصنيف يحتوي اسمه العربي المطبع على القيمة المدخلة. استخدم الاسم الكامل من الفهرس لتجنب التطابق الغامض.",
    ],
    "AzkarCategoryResponse",
    [
      p(
        "category",
        "path",
        true,
        { type: "string", minLength: 1 },
        "أذكار الصباح",
        "Arabic category name, URL-encoded as one path segment.",
        "اسم التصنيف العربي، مرمّز كمقطع واحد من المسار.",
      ),
    ],
    "client.azkar.getByCategory('أذكار الصباح')",
    [400, 404, 503],
  ),
  e(
    "/azkar/search",
    "azkar/search",
    "searchAzkar",
    ["Search azkar text", "البحث في الأذكار"],
    [
      "Returns {success, total, data: [...]}, with category and item for each hit. total is the number returned, capped by limit.",
      "يعيد {success, total, data: [...]} مع التصنيف والذكر لكل نتيجة. total هو عدد النتائج المعادة بعد تطبيق limit.",
    ],
    "AzkarSearchResponse",
    [{ ...search(200)[0], example: "الله" }, search(200)[1]],
    null,
    [400, 404, 503],
    [
      "SDK 1.0.2 has an envelope mismatch in client.azkar.search(). Use fetch or the compatibility helper in the SDK guide.",
      "توجد مشكلة في فك الاستجابة داخل client.azkar.search() في SDK 1.0.2. استخدم fetch أو الدالة البديلة في دليل SDK.",
    ],
  ),
  e(
    "/azkar/random",
    "azkar/random",
    "getRandomZekr",
    ["Random zekr", "ذكر عشوائي"],
    [
      "Chooses one item from all cached categories. Random selection happens per request.",
      "يختار ذكرًا من جميع التصنيفات المخزّنة. يتم الاختيار العشوائي عند كل طلب.",
    ],
    "AzkarPickResponse",
    [],
    "client.azkar.random()",
    [404, 503],
  ),
  e(
    "/hadith",
    "hadith/books",
    "listHadithBooks",
    ["Hadith books", "كتب الحديث"],
    [
      "Returns book IDs, names and available counts from the active provider. Discover IDs here instead of assuming a fixed list.",
      "يعيد معرّفات الكتب وأسماءها وأعداد الأحاديث من المصدر المستخدم. استخرج المعرّفات هنا بدل افتراض قائمة ثابتة.",
    ],
    "HadithBookListResponse",
    [],
    "client.hadith.listBooks()",
  ),
  e(
    "/hadith/{book}",
    "hadith/book",
    "getHadithBook",
    ["Hadith range", "نطاق أحاديث"],
    [
      "Returns book, available and hadiths inside data. Both range endpoints are inclusive; omitted from defaults to 1 and omitted to defaults to from + 29.",
      "يعيد book وavailable وhadiths داخل data. طرفا النطاق مشمولان؛ from الافتراضي 1 وto الافتراضي from + 29.",
    ],
    "HadithListResponse",
    [
      book(),
      p(
        "from",
        "query",
        false,
        { type: "integer", minimum: 1, default: 1 },
        1,
        "First hadith number, inclusive.",
        "رقم أول حديث، وهو مشمول.",
      ),
      p(
        "to",
        "query",
        false,
        { type: "integer", minimum: 1 },
        30,
        "Last hadith number, inclusive. Use at most 300 items: to = from + 299.",
        "رقم آخر حديث، وهو مشمول. استخدم 300 حديث كحد أقصى: to = from + 299.",
      ),
    ],
    "client.hadith.getBook('bukhari', { from: 1, to: 30 })",
    [400, 503],
    [
      "The API currently rejects to - from > 300, so it accepts 301 inclusive items. SDK 1.0.2 rejects more than 300 when both bounds are supplied. Use 300 or fewer for compatibility. An empty range can return 200 with hadiths: [].",
      "يرفض API حاليًا to - from > 300، فيقبل 301 عنصرًا عند شمول الطرفين. يرفض SDK 1.0.2 أكثر من 300 عند إرسال الطرفين. استخدم 300 أو أقل للتوافق. قد يعيد النطاق الفارغ 200 مع hadiths: [].",
    ],
  ),
  e(
    "/hadith/{book}/{number}",
    "hadith/get",
    "getHadith",
    ["Get a hadith", "حديث برقم"],
    [
      "Returns a narration by its book-local number. The response has no grading or chain-of-transmission fields.",
      "يعيد الحديث برقم داخل الكتاب. الاستجابة لا تحتوي حقول الحكم على الحديث أو الإسناد.",
    ],
    "HadithResponse",
    [
      book(),
      p(
        "number",
        "path",
        true,
        { type: "integer", minimum: 1 },
        1,
        "Positive hadith number within the book.",
        "رقم حديث موجب داخل الكتاب.",
      ),
    ],
    "client.hadith.getByNumber('bukhari', 1)",
    [400, 404, 503],
  ),
  e(
    "/hadith/random",
    "hadith/random",
    "getRandomHadith",
    ["Random hadith", "حديث عشوائي"],
    [
      "Picks a book, then a number from its available count. Optionally restrict the book. The result contains book and hadith.",
      "يختار كتابًا ثم رقم حديث وفق العدد المتاح. يمكن تقييد الكتاب. تحتوي النتيجة book وhadith.",
    ],
    "RandomHadithResponse",
    [
      p(
        "book",
        "query",
        false,
        { type: "string" },
        "bukhari",
        "Optional exact book ID. An unknown ID returns 404.",
        "معرّف كتاب مطابق اختياري. المعرّف المجهول يعيد 404.",
      ),
    ],
    "client.hadith.random({ book: 'bukhari' })",
    [404, 503],
  ),
  e(
    "/prayer/times",
    "prayer/times",
    "getPrayerTimes",
    ["Prayer times", "مواقيت الصلاة"],
    [
      "Provide latitude + longitude or city + country. With both pairs, Aladhan coordinates are tried before Aladhan city lookup.",
      "أرسل latitude وlongitude أو city وcountry. عند إرسال الزوجين، تُجرّب إحداثيات Aladhan قبل البحث باسم المدينة.",
    ],
    "PrayerTimesResponse",
    [
      date(),
      ...coords(false, false),
      p(
        "city",
        "query",
        false,
        { type: "string" },
        "Mecca",
        "Required with country when coordinates are not supplied.",
        "مطلوب مع country عند عدم إرسال الإحداثيات.",
      ),
      p(
        "country",
        "query",
        false,
        { type: "string" },
        "SA",
        "Country for city lookup. Send together with city.",
        "الدولة للبحث عن المدينة. أرسلها مع city.",
      ),
      p(
        "method",
        "query",
        false,
        { type: "integer" },
        4,
        "Aladhan calculation method ID. Omitted uses the provider default.",
        "معرّف طريقة الحساب لدى Aladhan. عند حذفه يستخدم المصدر افتراضيه.",
      ),
    ],
    "client.prayer.getTimes({ latitude: 21.4225, longitude: 39.8262, method: 4 })",
    [400, 503],
    [
      "pray.zone fallback is available only for coordinate requests dated today on the API server. It does not receive method, and may omit method and coordinates. Inspect apiName before assuming identical calculation settings. This controller validates numeric coordinates but does not enforce geographic bounds; SDK validation does.",
      "يتاح بديل pray.zone لطلبات الإحداثيات بتاريخ اليوم على خادم API فقط. لا يستقبل method وقد يحذف method وcoordinates من النتيجة. افحص apiName قبل افتراض ثبات طريقة الحساب. يتحقق هذا المتحكم من كون الإحداثيات أرقامًا دون فرض حدودها الجغرافية؛ يفرض SDK الحدود.",
    ],
  ),
  e(
    "/hijri/today",
    "hijri/today",
    "getToday",
    ["Today in both calendars", "تاريخ اليوم بالتقويمين"],
    [
      "Converts the API server’s current Gregorian date through Aladhan. It does not use the browser’s timezone.",
      "يحوّل تاريخ خادم API الميلادي الحالي عبر Aladhan. لا يستخدم المنطقة الزمنية للمتصفح.",
    ],
    "HijriResponse",
    [],
    "client.hijri.today()",
  ),
  e(
    "/hijri/from-gregorian",
    "hijri/from-gregorian",
    "fromGregorian",
    ["Gregorian to Hijri", "من الميلادي إلى الهجري"],
    [
      "Returns both calendar representations. Aladhan is the only configured source.",
      "يعيد تمثيل التاريخ بالتقويمين. Aladhan هو المصدر الوحيد المضبوط.",
    ],
    "HijriResponse",
    [date()],
    "client.hijri.fromGregorian('01-01-2026')",
    [400, 503],
  ),
  e(
    "/hijri/to-gregorian",
    "hijri/to-gregorian",
    "toGregorian",
    ["Hijri to Gregorian", "من الهجري إلى الميلادي"],
    [
      "Converts a required Hijri date. Returned month and weekday names come from the provider.",
      "يحوّل تاريخًا هجريًا مطلوبًا. تأتي أسماء الأشهر وأيام الأسبوع من المصدر.",
    ],
    "HijriResponse",
    [date(true, true)],
    "client.hijri.toGregorian('01-09-1447')",
    [400, 503],
  ),
  e(
    "/qibla",
    "qibla/direction",
    "getQibla",
    ["Qibla direction", "اتجاه القبلة"],
    [
      "Returns degrees clockwise from true north. Tries Aladhan, then calculates the great-circle bearing locally.",
      "يعيد الزاوية بالدرجات باتجاه عقارب الساعة من الشمال الحقيقي. يجرّب Aladhan ثم يحسب الاتجاه محليًا على الدائرة العظمى.",
    ],
    "QiblaResponse",
    coords(true, true),
    "client.qibla.getDirection(21.4225, 39.8262)",
    [400, 503],
    [
      "This is a geographic bearing, not a device compass reading. Magnetic declination and device orientation are outside this endpoint.",
      "هذه زاوية جغرافية وليست قراءة بوصلة الجهاز. الانحراف المغناطيسي واتجاه الجهاز خارج وظيفة هذا المسار.",
    ],
  ),
];
